version: '3.7'

services:
  influx-ingress:
    restart: always
    image: whatwewant/nginx-basic-auth:v0.0.5
    ports:
      - ${SERVICE_INFLUX_HOST}:${SERVICE_INFLUX_PORT}:80
    depends_on:
      - influx
    environment:
      BASIC_AUTH_USERNAME: ${SERVICE_INFLUX_ADMIN_USERNAME}
      BASIC_AUTH_PASSWORD: ${SERVICE_INFLUX_ADMIN_PASSWORD}
      PROXY_PASS: http://influx:8086
      CLIENT_MAX_BODY_SIZE: 0
    volumes:
      - ${SERVICE_INFLUX_HTPASSWD_CONFIG}:/etc/nginx/.htpasswd

  influx:
    restart: always
    image: influxdb:${SERVICE_INFLUX_VERSION}
    # ports:
    #   - ${SERVICE_INFLUX_HOST}:${SERVICE_INFLUX_PORT}:8086
      # - 127.0.0.1:8083:8083
      # - 127.0.0.1:8090:8090
    environment:
      TZ: Asia/Shanghai
      INFLUXDB_HTTP_LOG_ENABLED: 'false'
    volumes:
      - ${SERVICE_DATA}:/var/lib/influxdb


networks:
  default:
    external: true
    name: compose-ingress
